services:
  - type: web
    name: btcsirepository
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn G12Research.wsgi:application
    healthCheckPath: /healthcheck/
    healthCheckInterval: 30
    healthCheckTimeout: 10
    
  - type: cron
    name: sample-cron-job
    env: python
    schedule: "*/5 * * * *"
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py sample_cron